# Generated by Django 3.2.7 on 2021-09-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallinks',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_links',
        ),
        migrations.AddField(
            model_name='profile',
            name='address_1',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Present Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_2',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Present Address cont..'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='City: Dhaka'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Country: Bangladesh'),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL Link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub URL Link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Linkedin URL Link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL Link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Personal Website Link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube URL Link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Zip Code: 1234'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Full Name'),
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
        migrations.DeleteModel(
            name='SocialLinks',
        ),
    ]
